name: SEDP
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - pandas>=2.2,<2.4
  - numpy>=1.26,<3
  - matplotlib>=3.8,<4
  - jupyter
  - notebook
  - ipykernel
  - streamlit>=1.40,<2
  - plotly>=5,<7
  - pyarrow
  - protobuf>=4,<6

  - pip:
      - fastf1>=3.8,<4